{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "dropout_rate", "default": 0.2, "conditions": [], "values": [0.2, 0.3, 0.4], "ordered": true}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"units": 512, "dropout_rate": 0.4, "learning_rate": 0.0001, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/Cast' defined at (most recent call last):\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel_launcher.py\", line 18, in <module>\n      app.launch_new_instance()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n      app.start()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 739, in start\n      self.io_loop.start()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 205, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n      await self.process_one()\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n      await dispatch(*args)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n      await result\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n      await super().execute_request(stream, ident, parent)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n      reply_content = await reply_content\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n      res = shell.run_cell(\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3009, in run_cell\n      result = self._run_cell(\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3064, in _run_cell\n      result = runner(coro)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3269, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3448, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/9d/wb464w3106z5ftt3ymdcn6t00000gn/T/ipykernel_94944/740105347.py\", line 13, in <module>\n      train_and_evaluate_model(\n    File \"/var/folders/9d/wb464w3106z5ftt3ymdcn6t00000gn/T/ipykernel_94944/4186584697.py\", line 7, in train_and_evaluate_model\n      tuner = perform_hyperparameter_tuning(model_name, base_model_func, train_dataset, val_dataset, num_classes)\n    File \"/var/folders/9d/wb464w3106z5ftt3ymdcn6t00000gn/T/ipykernel_94944/1498368933.py\", line 16, in perform_hyperparameter_tuning\n      tuner.search(train_dataset, validation_data=val_dataset, epochs=max_epochs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n      self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n      self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n      results = self.run_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n      return super().run_trial(trial, *fit_args, **fit_kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n      obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n      results = self.hypermodel.fit(hp, model, *args, **kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n      return model.fit(*args, **kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/training.py\", line 1742, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/training.py\", line 1338, in train_function\n      return step_function(self, iterator)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/training.py\", line 1322, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/training.py\", line 1303, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/training.py\", line 1081, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/training.py\", line 1139, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/losses.py\", line 142, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/losses.py\", line 268, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/losses.py\", line 2354, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/backend.py\", line 5712, in sparse_categorical_crossentropy\n      target = cast(target, \"int64\")\n    File \"/Users/nipunaupeksha/miniconda3/envs/msc/lib/python3.8/site-packages/keras/src/backend.py\", line 2305, in cast\n      return tf.cast(x, dtype)\nNode: 'sparse_categorical_crossentropy/Cast'\n2 root error(s) found.\n  (0) UNIMPLEMENTED:  Cast string to int64 is not supported\n\t [[{{node sparse_categorical_crossentropy/Cast}}]]\n  (1) CANCELLED:  Function was cancelled before it was started\n0 successful operations.\n0 derived errors ignored. [Op:__inference_train_function_4053]\n"}